---
apiVersion: v1
kind: Namespace
metadata:
  name: code-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server-config
  namespace: code-server
data:
  config.yaml: |
    bind-addr: 0.0.0.0:8080
    auth: password
    password: insert_password_here
    cert: false
    user-data-dir: /home/code/data
    extensions-dir: /home/code/extensions
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-app
  namespace: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server-app
  template:
    metadata:
      labels:
        app: code-server-app
    spec:
      containers:
        - name: code-server
          image: jasondewitt/code-server:latest
          command: ["/usr/bin/code-server","--config","/home/code/config.yaml"]
          volumeMounts:
          - name: config-volume
            mountPath: /home/code/config.yaml
            subPath: config.yaml
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: code-server-config
---
apiVersion: v1
kind: Service
metadata:
  name: code-server-service
  namespace: code-server
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: tcp
  selector:
    app: code-server-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: code-server-ingress
  namespace: code-server
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: code-server-service
          servicePort: 80